// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://xhhxldktbdkzwrnvuyuw.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InhoaHhsZGt0YmRrendybnZ1eXV3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDU0MjU0OTgsImV4cCI6MjA2MTAwMTQ5OH0.Z3xVw8cPuAvtG6MBGannFnrhPP_qfzgzE6rQno6X11Q";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);